name: be brilliant
favicon: null
layout_spectrum: 0.299345385748893
typography_spectrum: 0.5106474510394037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.49344380339607596
  lightness: 0.5222742429468781
  saturation: 0.38397297519259155
  rhythmicContrast: 0.17348148534074426
purpose: []
